config/routes.rb
Rails.application.routes.draw do

  get 'users/new'
  get 'sessions/new'
  

  root    'principal#home'
  get     'home'     => 'principal#home'
  get     'help'     => 'principal#help'
  get     'contact'  => 'principal#contact'
  get     'about'    => 'principal#about'
  get     'news'     => 'principal#news'

  get    'signup'    => 'users#new'
  get    'login'     => 'sessions#new'
  post   'login'     => 'sessions#create'
  delete 'logout'    => 'sessions#destroy'

  resources :users



end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/principal_controller.rb
class PrincipalController < ApplicationController
  	
  	def index
  	@saludo='Sistema Integral de Control y Mantenimiento de Puentes - MTC';
  	end
	
	def home
  	
  	end
  	
  	def news
  	
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new

  end

  def create
     user = User.find_by(Correo: params[:session][:Correo].downcase)
    if user && user.authenticate(params[:session][:Contraseña])
    	log_in user
    	redirect_to user

    else
      # Create an error message.
      flash[:danger] = 'Correo y/o contraseña inválidos' 
      render 'new'
    end
  end

  def destroy
  	log_out
    redirect_to root_url
  end

end

    

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  	@user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
  	@user = User.new(user_params)
    flash[:success] = "¡Bienvenido al Sistema Integral de Control y mantenimiento de Puentes!"

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuario creado correctamente' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Usuario actualizado correctamente' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuario eliminado correctamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:Nombre, :Correo, :Contraseña, :Confirmar_contraseña)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def full_title(page_title = '')
    base_title = "Sistema de Control y Mantenimiento de Puentes - MTC"
    	if page_title.empty?
     	 base_title
    	else
    	 page_title + " | " + base_title+ " | " 
    
    	end
  	end
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

   # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

	def logged_in?
		!current_user.nil?
 	end

 	def log_out
    	session.delete(:user_id)
    	@current_user = nil
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Proyecto: <a href="http://www.sistemamtc.gob.pe/">Sistema de Control y Mantenimiento de Puentes - MTC</a>
    Por: <a href="">Multriton SAC</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://proviasnac.gob.pe/">Noticias</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
        

          
        

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
<head>
  <title>Sistema MTC</title>
  <!--<title><%= full_title(yield(:title)) %></title>-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %>
</head>
<body background-image: url("/home/jhunely/Escritorio/Proyectos_RoR/Sistema_MTC/app/assets/images/1.jpg");>
<%= render 'layouts/header' %>
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Sistema MTC", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Help",   "#" %></li>
            <li><%= link_to "Log in", login_path %></li>
          </ul>
        </nav>
      </div>
</header>
	
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %>
        </div>
      <% end %>
    </div>
    <div class="container">
     <%= yield %> 
     <%= render 'layouts/footer' %>
    </div>
</body>
</html>

app/views/principal/home.html.erb
<% provide(:title, "home") %>
<div class="container">
		<div id="img" align="center" >
   			<%= image_tag "puente.jpg"%>
		</div>
		<div class="container" align="justify">
		<strong>VISIÓN: </strong>Un país con servicios de transportes y comunicaciones eficientes, integrado nacional e internacionalmente, que contribuya a la competitividad de las actividades productivas y mejore la calidad de vida de nuestra población, especialmente de los más pobres.
		<br>
		<br>
		<strong>MISIÓN: </strong>Preparación, gestión, administración y ejecución de proyectos de  infraestructura de transporte relacionada a la Red Vial Nacional, así como de la gestión y control de actividades y recursos económicos que se emplean para el mantenimiento y seguridad de la carreteras y puentes de la Red Vial Nacional.
		
		</div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :Nombre %>
  </div>
  <div class="field">
    <%= f.label :Correo %><br>
    <%= f.text_field :Correo %>
  </div>
  <div class="field">
    <%= f.label :Contraseña,"Contraseña"%>
    <%= f.password_field :Contraseña %>
  </div>
  <div class="field">
    <%= f.label :Confirmar_contraseña, "Confirmar Contraseña" %>
    <%= f.password_field :Confirmar_contraseña %>
  </div>
 
     <%= f.submit "Registrar", class: "btn btn-primary" %>

<% end %>

app/views/users/edit.html.erb
<h1>Actualizar Perfil</h1>

<%= render 'form' %>


<%= link_to 'Ver', @user %> |
<%= link_to 'Atrás', users_path %>

app/views/users/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1>Listar Usuarios</h1>

 <center><table>
  <thead>
    <tr>
      <th>Nombre:</th>
      <th>Correo:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.Nombre %></td>
        <td><%= user.Correo %></td>
        <td><%= link_to 'Ver', user %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <td><%= link_to 'Eliminar', user, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Usuario', new_user_path %>
</center>

app/views/users/new.html.erb
<!--<% provide(:title, 'Sign up') %>-->
<h1>Regístrate</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <strong>Nombre:</strong>
  <%= @user.Nombre %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @user.Correo %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Atrás', users_path %>